### ISSUE TITLE
Use proper html & sign

### ISSUE THREAD

**Issue by sangjunp4rk** [suddenmoves/prj-rev-bwfs-dasmoto#1]
Use the html & sign instead of just &, which is `&amp;` You did it correctly for the title but make sure to use it everywhere and be consistent. Continue doing this in the future for all special symbols. You can find all of them here https://www.ascii.cl/htmlcodes.htm

https://github.com/suddenmoves/prj-rev-bwfs-dasmoto/blob/master/dasmoto/index.html#L11

**Comment by suddenmoves** [comment]
Agreed, this need to be consistent, though as it turns out the W3C validator is happy with & or &amp;
